version: '3'
services:
  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./proxy.conf:/etc/nginx/proxy.conf:ro
    ports:
      - 8080:8080
    links:
      - nextgen
      - locomotive
    depends_on:
      - nextgen
      - locomotive
  nextgen:
    build:
      context: ../msri.nextgen
    expose:
      - 3000
    links:
      - mysql
      - redis
    depends_on:
      - mysql
      - redis
  locomotive:
    build:
      context: ../msri.locomotive
    expose:
      - 3000
    links:
      - mongo
      - redis
    depends_on:
      - mongo
      - redis
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: msri_nextgen
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
  mongo:
    image: mongo
    restart: always
    expose:
      - 8081
    volumes:
      - mongo-data:/data/db
  redis:
    image: redis
    expose:
      - 6379
  solr:
    image: stephenlawrence/docker-solr
    expose:
      - 8983
    volumes:
      - solr-data:/var/solr
volumes:
  mysql-data:
  mongo-data:
  solr-data:
